export type IAEditorCategory = {
  slug: string;
  title: string;
  description: string;
  intro: string;
  businessQuestion: string;
  metrics: string[];
  related: string[];
};

export type IATool = {
  slug: string;
  name: string;
  company: string;
  categorySlug: string;
  category: string;
  status: string;
  useCase: string;
  bestFor: string;
  practicalUses: string[];
  metrics: string[];
  attention: string[];
  source: string;
  sourceLabel: string;
  reviewedAt: string;
};

export const categories: IAEditorCategory[] = [
  {
    slug: "agentes",
    title: "Agentes e operação",
    description: "Copilotos e agentes que analisam dados, executam tarefas e reduzem trabalho operacional.",
    intro: "Agentes de IA deixam de ser apenas interfaces de resposta quando recebem contexto da operação e permissão para executar ações. No e-commerce, isso pode significar analisar dados, alterar cadastros, apoiar merchandising, orientar equipes ou automatizar fluxos com supervisão humana.",
    businessQuestion: "Quais tarefas repetitivas ou decisões operacionais consomem horas da equipe sem criar diferenciação para o negócio?",
    metrics: ["Horas operacionais economizadas", "Tempo médio para concluir tarefas", "Taxa de correção/retrabalho", "Impacto financeiro por fluxo automatizado"],
    related: ["analytics", "crm", "atendimento"],
  },
  {
    slug: "atendimento",
    title: "Atendimento e vendas",
    description: "Assistentes que respondem dúvidas, recomendam produtos e apoiam pré e pós-venda.",
    intro: "A IA em atendimento já atua em pré-venda e pós-venda, mas o ganho real depende de base de conhecimento, integração com pedidos e regras claras de transferência para humanos. O objetivo não é apenas reduzir tickets: é melhorar resolução, velocidade e conversão sem comprometer confiança.",
    businessQuestion: "Quais dúvidas e solicitações se repetem e quais delas podem ser resolvidas com segurança usando dados da loja?",
    metrics: ["Taxa de resolução automática", "Tempo de primeira resposta", "Conversão assistida", "CSAT/NPS por canal"],
    related: ["crm", "agentes", "personalizacao"],
  },
  {
    slug: "crm",
    title: "CRM e automação",
    description: "IA aplicada a segmentação, jornadas, campanhas, retenção e relacionamento.",
    intro: "Em CRM, a IA ganha valor quando cruza comportamento, histórico de compra e contexto do cliente para priorizar mensagens, recomendações e ações. O ponto central é reduzir comunicação genérica e aumentar relevância ao longo da jornada.",
    businessQuestion: "A operação consegue diferenciar cliente novo, recorrente, inativo e de alto valor com mensagens e ofertas adequadas?",
    metrics: ["Receita por destinatário", "Taxa de recompra", "LTV", "Receita incremental de automações"],
    related: ["personalizacao", "atendimento", "analytics"],
  },
  {
    slug: "busca-descoberta",
    title: "Busca e descoberta",
    description: "Busca semântica, recomendação e descoberta de produtos com intenção mais complexa.",
    intro: "Busca interna e descoberta de produtos estão migrando de correspondência literal para entendimento de intenção. Isso exige catálogo bem estruturado, atributos completos e uma camada de experiência capaz de responder a consultas mais naturais.",
    businessQuestion: "O cliente encontra o produto certo quando pesquisa pelo problema, uso ou intenção — e não apenas pelo nome exato do SKU?",
    metrics: ["Taxa de busca sem resultado", "Conversão após busca", "CTR de resultados", "Receita por sessão com busca"],
    related: ["personalizacao", "seo-geo", "commerce-agentivo"],
  },
  {
    slug: "personalizacao",
    title: "Personalização e CRO",
    description: "Experiências, vitrines e ofertas adaptadas ao comportamento do comprador.",
    intro: "Personalização com IA deve ser tratada como disciplina de conversão, não como decoração. Quanto melhor o dado de produto e comportamento, maior a capacidade de ajustar vitrines, recomendações, bundles e experiências sem perder controle de negócio.",
    businessQuestion: "Quais pontos da jornada têm volume suficiente para testar personalização e medir impacto incremental?",
    metrics: ["Taxa de conversão", "AOV", "Receita por sessão", "Uplift de testes controlados"],
    related: ["analytics", "crm", "busca-descoberta"],
  },
  {
    slug: "ads",
    title: "Ads e aquisição",
    description: "Otimização de mídia, criativos, segmentação e Shopping com modelos de IA.",
    intro: "A IA já está embutida nas principais plataformas de mídia. Para e-commerce, o diferencial passa a ser a qualidade do feed, dos criativos, da mensuração e das páginas de destino — os insumos usados pelos modelos para decidir onde e como distribuir investimento.",
    businessQuestion: "Seu feed, tracking e conteúdo dão aos algoritmos sinais suficientes para otimizar por margem e valor, e não apenas por volume?",
    metrics: ["ROAS/POAS", "CPA", "Valor de conversão", "Margem após mídia"],
    related: ["analytics", "seo-geo", "imagem-video"],
  },
  {
    slug: "seo-geo",
    title: "Conteúdo, SEO e GEO",
    description: "Conteúdo, catálogo e estrutura técnica preparados para busca tradicional e respostas de IA.",
    intro: "SEO e GEO convergem em um princípio: tornar produtos, categorias e expertise compreensíveis por mecanismos de busca e sistemas generativos. Isso depende de conteúdo útil, entidades consistentes, arquitetura interna, dados estruturados e fontes confiáveis.",
    businessQuestion: "Seu site explica claramente o que vende, para quem, com quais atributos e por que sua informação merece ser usada como referência?",
    metrics: ["Cliques orgânicos qualificados", "Cobertura de páginas indexáveis", "Conversões orgânicas", "Menções/citações em experiências generativas"],
    related: ["busca-descoberta", "commerce-agentivo", "analytics"],
  },
  {
    slug: "imagem-video",
    title: "Imagem e vídeo",
    description: "Criação e edição de ativos de produto, anúncios e conteúdo em escala.",
    intro: "IA generativa reduz o custo de produção criativa, mas a vantagem real aparece quando existe direção de marca, revisão humana e um sistema para transformar ativos em variações testáveis de mídia e catálogo.",
    businessQuestion: "Quais ativos hoje atrasam campanhas, lançamentos ou atualização de catálogo e podem ser produzidos com supervisão em menos tempo?",
    metrics: ["Tempo por ativo", "Custo por variação", "CTR por criativo", "Taxa de aprovação/revisão"],
    related: ["ads", "seo-geo", "personalizacao"],
  },
  {
    slug: "analytics",
    title: "Analytics e BI",
    description: "Leitura de dados, detecção de padrões e apoio à tomada de decisão.",
    intro: "O maior ganho de IA em analytics não é criar mais dashboards, mas encurtar o caminho entre dado, hipótese e ação. A base precisa continuar confiável: eventos, receita, margem, canais e definições devem estar consistentes antes da camada de IA.",
    businessQuestion: "Quanto tempo leva entre perceber uma anomalia e chegar a uma decisão operacional com evidência suficiente?",
    metrics: ["Tempo para insight", "Cobertura de tracking", "Erro entre fontes", "Valor financeiro das ações geradas"],
    related: ["ads", "personalizacao", "agentes"],
  },
  {
    slug: "precificacao",
    title: "Precificação",
    description: "Monitoramento competitivo e suporte algorítmico a decisões de preço.",
    intro: "IA e automação podem apoiar monitoramento de concorrência e regras de preço, mas precisam respeitar margem, estoque, posicionamento e restrições comerciais. O objetivo é aumentar qualidade da decisão, não reagir automaticamente a qualquer movimento externo.",
    businessQuestion: "A operação consegue responder a mudanças de preço e estoque sem sacrificar margem ou posicionamento?",
    metrics: ["Margem bruta", "Índice de competitividade", "Giro de estoque", "Receita incremental por regra"],
    related: ["analytics", "logistica", "personalizacao"],
  },
  {
    slug: "logistica",
    title: "Logística e operação",
    description: "Previsão, roteirização, atendimento operacional e automação de backoffice.",
    intro: "Em logística, IA funciona melhor quando conectada a dados reais de demanda, estoque, SLA e custo. Casos de uso incluem previsão, exceções operacionais, suporte interno e priorização de tarefas.",
    businessQuestion: "Quais decisões logísticas ainda dependem de planilhas, conferência manual ou reação tardia a exceções?",
    metrics: ["OTIF/SLA", "Custo por pedido", "Ruptura", "Tempo de resolução de exceções"],
    related: ["analytics", "precificacao", "agentes"],
  },
  {
    slug: "commerce-agentivo",
    title: "Commerce agentivo",
    description: "Produtos descobertos, comparados e comprados dentro de interfaces conversacionais.",
    intro: "No commerce agentivo, agentes e interfaces conversacionais passam a participar da descoberta, comparação e, em alguns fluxos, da própria compra. Isso muda a prioridade do lojista: catálogo, disponibilidade, preço, metadados e autoridade precisam ser legíveis por sistemas além da interface tradicional da loja.",
    businessQuestion: "Seu catálogo está estruturado para ser entendido e atualizado fora do front-end tradicional da loja?",
    metrics: ["Cobertura de feed", "Qualidade dos atributos", "Sessões/conversões vindas de novos canais", "Atualização e consistência de preço/estoque"],
    related: ["seo-geo", "busca-descoberta", "agentes"],
  },
];

export const tools: IATool[] = [
  {
    slug: "chatgpt-shopping",
    name: "ChatGPT Shopping e Product Feeds",
    company: "OpenAI",
    categorySlug: "commerce-agentivo",
    category: "Commerce agentivo",
    status: "Descoberta de produtos e integração de catálogo",
    useCase: "Produtos podem aparecer em experiências de compra do ChatGPT a partir de metadados de comerciantes e produtos. Comerciantes elegíveis também podem fornecer feeds diretos para manter informações atualizadas.",
    bestFor: "Lojistas que querem preparar catálogo, disponibilidade, preço e metadados para novos canais de descoberta e compra assistida por IA.",
    practicalUses: ["Revisar qualidade de título, descrição e atributos de produto", "Garantir consistência de preço e disponibilidade", "Avaliar elegibilidade e integração de feeds", "Medir tráfego e conversões vindas de experiências de IA"],
    metrics: ["Cobertura do catálogo", "Atualização de preço/estoque", "Sessões assistidas por IA", "Conversão por origem"],
    attention: ["Resultados de compras são independentes de anúncios", "Disponibilidade de recursos e integrações pode variar por mercado e elegibilidade", "Feeds não substituem qualidade técnica e editorial das páginas de produto"],
    source: "https://help.openai.com/pt-br/articles/11128490-shopping-with-chatgpt-search",
    sourceLabel: "OpenAI Help Center — Compras com a Busca do ChatGPT",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "shopify-sidekick",
    name: "Sidekick",
    company: "Shopify",
    categorySlug: "agentes",
    category: "Agentes e operação",
    status: "Assistente de IA nativo do admin Shopify",
    useCase: "O Sidekick usa o contexto da loja para responder perguntas, analisar dados, gerar conteúdo, editar produtos, gerenciar pedidos e apoiar tarefas dentro do admin da Shopify.",
    bestFor: "Operações Shopify que querem reduzir trabalho manual e acelerar análise e execução sem sair do ambiente da plataforma.",
    practicalUses: ["Analisar indicadores e contexto da loja", "Editar produtos e conteúdo", "Apoiar gerenciamento de pedidos", "Criar apps e habilidades para rotinas recorrentes"],
    metrics: ["Horas economizadas", "Tempo por tarefa", "Retrabalho após revisão", "Número de fluxos recorrentes automatizados"],
    attention: ["Mudanças devem ser revisadas antes da aplicação", "Permissões e acesso a dados precisam ser controlados", "Resultados de IA podem conter erros e exigem validação"],
    source: "https://help.shopify.com/pt-BR/manual/ai-powered-tools/sidekick",
    sourceLabel: "Shopify Help Center — Sidekick",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "shopify-magic",
    name: "Shopify Magic",
    company: "Shopify",
    categorySlug: "imagem-video",
    category: "Conteúdo, imagem e mídia",
    status: "Suite de recursos de IA da Shopify",
    useCase: "O Shopify Magic reúne recursos para criar descrições, e-mails, páginas, respostas e mídia, além de apoiar geração e edição de ativos no admin.",
    bestFor: "Times que precisam acelerar produção de catálogo e comunicação mantendo revisão editorial e direção de marca.",
    practicalUses: ["Descrições de produto e páginas", "E-mails e respostas", "Edição e geração de mídia", "Blocos e temas com assistência de IA"],
    metrics: ["Tempo de produção", "Taxa de aprovação", "CTR por ativo", "Conversão das páginas atualizadas"],
    attention: ["Conteúdo deve ser revisado antes da publicação", "Consistência de marca precisa ser definida fora da ferramenta", "Geração em escala sem revisão pode criar conteúdo repetitivo"],
    source: "https://help.shopify.com/pt-BR/manual/ai-powered-tools/shopify-magic",
    sourceLabel: "Shopify Help Center — Shopify Magic",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "klaviyo-customer-agent",
    name: "K:AI Customer Agent",
    company: "Klaviyo",
    categorySlug: "crm",
    category: "CRM e atendimento",
    status: "Agente de experiência do cliente",
    useCase: "A Klaviyo posiciona o K:AI Customer Agent como assistente 24/7 treinado com storefront e dados de clientes para responder perguntas, recomendar produtos e resolver solicitações em múltiplos canais.",
    bestFor: "Marcas com operação de CRM madura e necessidade de integrar atendimento, recomendação e contexto do cliente.",
    practicalUses: ["Responder dúvidas de pré-venda", "Recomendar produtos com contexto", "Apoiar pós-venda", "Conectar atendimento a dados de relacionamento"],
    metrics: ["Conversão assistida", "Receita por contato", "Resolução automática", "Taxa de recompra"],
    attention: ["Disponibilidade por idioma e canal pode variar", "Dados de cliente exigem governança e consentimento adequados", "Automação deve preservar critérios claros de handoff humano"],
    source: "https://www.klaviyo.com/products/customer-experience-hub/ecommerce-cx",
    sourceLabel: "Klaviyo — Ecommerce Customer Experience / K:AI",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "gorgias-ai-agent",
    name: "AI Agent",
    company: "Gorgias",
    categorySlug: "atendimento",
    category: "Atendimento e vendas",
    status: "Agente de suporte e shopping assistant",
    useCase: "O AI Agent da Gorgias atua em pré-venda e pós-venda, pode responder em diferentes canais e executar ações configuradas em ferramentas conectadas.",
    bestFor: "E-commerces Shopify com volume relevante de atendimento e oportunidade de automatizar dúvidas e ações repetitivas.",
    practicalUses: ["Rastreio e dúvidas de pedido", "Retornos e cancelamentos com regras", "Descoberta de produtos", "Handoff para equipe humana"],
    metrics: ["Taxa de resolução", "Tempo de resposta", "Conversão assistida", "Taxa de handoff"],
    attention: ["Alguns canais e recursos podem estar em beta", "Ações precisam ser explicitamente configuradas", "Monitoramento contínuo dos tickets é parte da operação"],
    source: "https://helpcenter.gorgias.com/en-US/ai-agent-explained-497772",
    sourceLabel: "Gorgias Help Center — AI Agent explained",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "nosto-huginn",
    name: "experience.AI + Huginn",
    company: "Nosto",
    categorySlug: "personalizacao",
    category: "Personalização e CRO",
    status: "Plataforma de experiência e agente central",
    useCase: "A Nosto usa experience.AI para ativar dados de cliente, produto e conteúdo em personalização, busca e merchandising; Huginn coordena agentes e oportunidades em fluxos de commerce experience.",
    bestFor: "Operações com tráfego e catálogo suficientes para testar personalização, merchandising, busca e otimização em escala.",
    practicalUses: ["Personalização onsite", "Merchandising e busca", "Bundles e recomendações", "Oportunidades e insights acionáveis"],
    metrics: ["Uplift de conversão", "AOV", "Receita por sessão", "Performance de testes"],
    attention: ["Resultados dependem de volume e qualidade de dados", "Recomendações precisam ser testadas contra baseline", "Nem todo recurso agente está necessariamente disponível no mesmo estágio para todas as contas"],
    source: "https://www.nosto.com/agentic-commerce/",
    sourceLabel: "Nosto — Agentic Commerce / Huginn",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "google-ai-max-shopping",
    name: "IA Max para campanhas do Shopping",
    company: "Google Ads",
    categorySlug: "ads",
    category: "Ads e aquisição",
    status: "Beta em 2026",
    useCase: "A IA Max para Shopping usa recursos de IA do Google para ampliar relevância de criativos, termos e páginas de destino em pesquisas de compra complexas e conversacionais.",
    bestFor: "Varejistas com Merchant Center, feed bem estruturado e mensuração suficiente para avaliar ganho incremental com controle de CPA, ROAS e margem.",
    practicalUses: ["Personalização de texto", "Expansão de URL final", "Cobertura de consultas de cauda longa", "Relatórios de termos, títulos e páginas de destino"],
    metrics: ["Valor de conversão", "CPA", "ROAS", "Margem após mídia"],
    attention: ["O recurso permanece beta", "É importante observar período de aprendizado antes de mudanças frequentes", "Ganho de volume não deve ser analisado sem margem e qualidade das conversões"],
    source: "https://support.google.com/google-ads/answer/17091277?hl=pt-BR",
    sourceLabel: "Google Ads Help — IA Max para Shopping",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "adobe-product-recommendations",
    name: "Product Recommendations",
    company: "Adobe Commerce",
    categorySlug: "personalizacao",
    category: "Personalização e recomendação",
    status: "Recomendações com Adobe AI",
    useCase: "O Adobe Commerce Product Recommendations usa Adobe AI e machine learning sobre comportamento agregado de compradores e dados do catálogo para gerar recomendações personalizadas na vitrine.",
    bestFor: "Operações Adobe Commerce que querem automatizar recomendação, cross-sell e up-sell com integração ao catálogo e à experiência da loja.",
    practicalUses: ["Recommended for you", "Cross-sell e up-sell", "Recomendações por comportamento", "Otimização por página e contexto"],
    metrics: ["Receita atribuída", "CTR de recomendações", "AOV", "Conversão por unidade de recomendação"],
    attention: ["A Adobe recomenda experimentar tipos e posicionamentos", "Privacidade e restrições do serviço precisam ser revisadas", "A recomendação deve complementar — não substituir — estratégia de merchandising"],
    source: "https://experienceleague.adobe.com/pt-br/docs/commerce/product-recommendations/overview",
    sourceLabel: "Adobe Experience League — Product Recommendations",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "algolia-neuralsearch",
    name: "NeuralSearch + Agentic Commerce",
    company: "Algolia",
    categorySlug: "busca-descoberta",
    category: "Busca e descoberta",
    status: "Busca híbrida, semântica e base para experiências agentivas",
    useCase: "A Algolia combina busca por palavras-chave e busca vetorial no NeuralSearch para interpretar consultas naturais e complexas. Em 2026, também passou a oferecer uma camada MCP para conectar agentes a catálogo, preço, estoque e regras de merchandising em tempo real.",
    bestFor: "E-commerces com catálogo amplo ou busca interna relevante que precisam melhorar relevância, reduzir buscas sem resultado e preparar descoberta de produtos para interfaces conversacionais.",
    practicalUses: ["Busca semântica e híbrida", "Ranqueamento com sinais de clique e conversão", "Personalização e merchandising", "Conexão de agentes a dados vivos de produto via MCP"],
    metrics: ["Conversão após busca", "Taxa de busca sem resultado", "CTR dos resultados", "Receita por sessão com busca"],
    attention: ["Qualidade do catálogo e dos eventos de clique/conversão afeta o aprendizado", "Busca vetorial não elimina a necessidade de regras comerciais", "Experiências agentivas exigem governança sobre preço, estoque e dados expostos"],
    source: "https://www.algolia.com/products/features/neuralsearch",
    sourceLabel: "Algolia — NeuralSearch",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "constructor-ai-shopping-agent",
    name: "AI Shopping Agent",
    company: "Constructor",
    categorySlug: "busca-descoberta",
    category: "Busca e descoberta",
    status: "Agente conversacional de descoberta de produtos",
    useCase: "O AI Shopping Agent da Constructor usa linguagem natural e contexto de catálogo para ajudar compradores a explorar produtos mesmo quando não sabem exatamente o que procurar, combinando intenção, comportamento e recomendações.",
    bestFor: "Varejistas com catálogo grande e jornada de descoberta complexa, especialmente quando filtros tradicionais não capturam bem intenção, ocasião de uso ou preferências do comprador.",
    practicalUses: ["Descoberta guiada por conversa", "Recomendações por intenção", "Comparação de opções", "Integração com busca, browse e recomendações da Constructor"],
    metrics: ["Conversão assistida", "Add-to-cart após interação", "Receita por visitante", "Engajamento com recomendações"],
    attention: ["O agente depende da qualidade de atributos e dados do catálogo", "É importante testar impacto incremental contra a experiência tradicional", "Tom, regras de merchandising e limites comerciais precisam continuar sob controle da marca"],
    source: "https://docs.constructor.com/docs/products-ai-shopping-agents-learn-about-ai-shopping-agent",
    sourceLabel: "Constructor Documentation — AI Shopping Agent",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "bloomreach-discovery-loomi",
    name: "Discovery + Loomi AI",
    company: "Bloomreach",
    categorySlug: "busca-descoberta",
    category: "Busca e descoberta",
    status: "Busca, personalização e merchandising orientados por IA",
    useCase: "Bloomreach Discovery usa Loomi AI para busca de e-commerce, interpretação de intenção, personalização, recomendações e automação de merchandising, incluindo experiências conversacionais de descoberta.",
    bestFor: "Operações com grande catálogo, equipe de merchandising e necessidade de unificar busca, personalização e regras comerciais em uma camada especializada de product discovery.",
    practicalUses: ["Busca semântica e natural language", "Personalização 1:1 e por segmento", "Recomendações", "Merchandising e otimização de categorias"],
    metrics: ["Revenue per visitor", "Conversão de usuários de busca", "AOV", "Tempo gasto em operação de merchandising"],
    attention: ["Resultados dependem de dados comportamentais e estrutura do catálogo", "Automação de ranking deve ser acompanhada por regras de margem, estoque e estratégia", "Claims de performance do fornecedor precisam ser validados no contexto de cada operação"],
    source: "https://www.bloomreach.com/en/products/ecommerce-search",
    sourceLabel: "Bloomreach — Ecommerce Search / Loomi AI",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "dynamic-yield-nextml-shopping-muse",
    name: "NextML + Shopping Muse",
    company: "Dynamic Yield by Mastercard",
    categorySlug: "personalizacao",
    category: "Personalização e CRO",
    status: "Deep learning para recomendação e assistente conversacional",
    useCase: "Dynamic Yield usa NextML para prever produtos de interesse a partir do comportamento do usuário e Shopping Muse para experiências conversacionais de descoberta alinhadas à voz e às regras da marca.",
    bestFor: "E-commerces com volume de tráfego e histórico comportamental suficientes para operar recomendações, personalização e experimentação com controle de marca.",
    practicalUses: ["Recomendações personalizadas", "Personalização de homepage e categorias", "Busca inteligente", "Shopping assistant com diretrizes conversacionais"],
    metrics: ["Uplift de conversão", "AOV", "CTR de recomendações", "Receita atribuída a experiências personalizadas"],
    attention: ["Alguns recursos exigem habilitação ou rollout gradual", "Personalização deve ser medida com grupos de controle", "Diretrizes de marca influenciam comunicação, mas não substituem governança de produto e catálogo"],
    source: "https://support.dynamicyield.com/hc/en-us/articles/360014180617-NextML-Algorithm-Deep-Learning-Recommendations",
    sourceLabel: "Dynamic Yield Knowledge Base — NextML",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "salesforce-agentforce-commerce",
    name: "Agentforce Commerce",
    company: "Salesforce",
    categorySlug: "commerce-agentivo",
    category: "Commerce agentivo",
    status: "Commerce Cloud orientado por agentes e dados conectados",
    useCase: "Agentforce Commerce conecta e-commerce, pedidos, merchandising e experiências de compra guiada com agentes que utilizam dados e contexto do ecossistema Salesforce.",
    bestFor: "Operações enterprise B2C ou B2B já conectadas ao ecossistema Salesforce e que buscam levar agentes para merchandising, descoberta, atendimento e jornadas transacionais.",
    practicalUses: ["Compras guiadas por agente", "Merchandising assistido", "Busca orientada por intenção", "Automação conectada a pedidos e dados de cliente"],
    metrics: ["Conversão", "AOV", "Produtividade de merchandising", "Tempo de resolução e operação"],
    attention: ["É uma arquitetura enterprise e o retorno depende de integração e qualidade de dados", "Claims de ganho publicados pela Salesforce não substituem teste próprio", "Permissões de agente e ações transacionais exigem controles de segurança e auditoria"],
    source: "https://www.salesforce.com/br/commerce/",
    sourceLabel: "Salesforce Brasil — Agentforce Commerce",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "google-product-studio",
    name: "Product Studio",
    company: "Google Merchant Center",
    categorySlug: "imagem-video",
    category: "Imagem e vídeo",
    status: "Criação e edição de ativos de produto com IA",
    useCase: "O Product Studio usa IA para criar cenas, remover fundos, aumentar resolução e, em mercados elegíveis, gerar vídeos a partir de produtos do Merchant Center ou do app Google & YouTube na Shopify.",
    bestFor: "Lojistas que precisam produzir variações visuais para Shopping, Performance Max e outros canais do Google sem depender de uma sessão fotográfica para cada adaptação.",
    practicalUses: ["Geração de cenários de produto", "Remoção de fundo", "Upscale de imagens", "Geração de vídeos em mercados suportados"],
    metrics: ["Tempo por ativo", "Quantidade de ativos aprovados", "CTR de Shopping", "ROAS por variação criativa"],
    attention: ["Recursos e disponibilidade variam por país", "A geração pode produzir resultados inesperados e requer revisão", "Imagens geradas por IA precisam preservar metadados e sinalizações exigidos pelo Google e por regulações aplicáveis"],
    source: "https://support.google.com/merchants/answer/13708167?hl=pt-BR",
    sourceLabel: "Google Merchant Center Help — Product Studio",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "adobe-firefly-product-shot",
    name: "Firefly Product Shot",
    company: "Adobe",
    categorySlug: "imagem-video",
    category: "Imagem e vídeo",
    status: "Geração de fotografia de produto e variações criativas",
    useCase: "O Adobe Firefly permite transformar imagens de produto em fotos de catálogo e lifestyle com diferentes ângulos, iluminação e fundos a partir de comandos e referências visuais.",
    bestFor: "Times de e-commerce e marketing que precisam acelerar produção de imagens para PDPs, campanhas, social e testes criativos mantendo direção visual consistente.",
    practicalUses: ["Fotos de produto com fundo branco", "Cenas lifestyle", "Variações de iluminação e composição", "Adaptação de ativos para campanhas"],
    metrics: ["Tempo de produção", "Custo por variação", "Taxa de aprovação", "CTR/conversão por criativo"],
    attention: ["Produtos e detalhes físicos devem ser conferidos para evitar representação incorreta", "Direitos de marca, embalagem e propriedade intelectual continuam sob responsabilidade do anunciante", "Ativos comerciais exigem revisão humana antes de publicação"],
    source: "https://www.adobe.com/products/firefly/features/ai-photo-editor/product-shot.html",
    sourceLabel: "Adobe Firefly — Product Shot Generator",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "intercom-fin-ecommerce",
    name: "Fin for Ecommerce",
    company: "Intercom",
    categorySlug: "atendimento",
    category: "Atendimento e vendas",
    status: "Agente de IA para suporte, vendas e shopping assistant",
    useCase: "Fin pode atuar em ecommerce como assistente de compras e agente de atendimento, usando dados de catálogo, pedido e sistemas conectados para recomendar produtos, responder dúvidas e executar ou orientar ações.",
    bestFor: "E-commerces que querem unir atendimento e descoberta de produtos em um agente com integração a Shopify e outros sistemas de suporte e CRM.",
    practicalUses: ["Recomendação de produtos", "Perguntas de pedido e entrega", "Suporte a devoluções", "Handoff para atendimento humano"],
    metrics: ["Taxa de resolução", "Conversão assistida", "CSAT", "Custo por resolução"],
    attention: ["Integrações e dados precisam ser configurados corretamente", "Políticas de devolução, garantia e exceções devem estar explícitas", "A taxa de automação deve ser analisada junto com qualidade e satisfação, não isoladamente"],
    source: "https://www.intercom.com/help/pt-BR/articles/9515824-o-que-e-fin",
    sourceLabel: "Intercom Help — O que é Fin?",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "zendesk-ai-retail",
    name: "Zendesk AI for Retail",
    company: "Zendesk",
    categorySlug: "atendimento",
    category: "Atendimento e vendas",
    status: "Agentes de IA e copilotos para operações de atendimento",
    useCase: "Zendesk AI para varejo automatiza solicitações como status de pedido, trocas, devoluções e inventário, conectando agentes a políticas, conhecimento, dados e workflows da operação.",
    bestFor: "Varejistas com operação de suporte multicanal que precisam automatizar volume repetitivo sem perder contexto e escalonamento humano.",
    practicalUses: ["Where is my order", "Trocas e devoluções", "Verificação de estoque", "Copilot para agentes humanos"],
    metrics: ["Taxa de resolução por IA", "CSAT", "Tempo médio de atendimento", "Custo por contato"],
    attention: ["Integrações com OMS, e-commerce e fulfillment determinam profundidade da automação", "Ações aprovadas devem ter regras e auditoria", "Automação de alto volume precisa ser monitorada por qualidade de resolução"],
    source: "https://www.zendesk.com/industries/retail/",
    sourceLabel: "Zendesk — AI-powered service software for retail",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "prisync-ai-pricing",
    name: "Prisync AI Pricing",
    company: "Prisync",
    categorySlug: "precificacao",
    category: "Precificação",
    status: "Monitoramento competitivo e repricing baseado em regras",
    useCase: "Prisync monitora preços e estoque de concorrentes e permite automatizar alterações de preço dentro de pisos, tetos, margens e regras definidas pelo lojista.",
    bestFor: "E-commerces que precisam acompanhar concorrência e ajustar preço em catálogos com volume suficiente para tornar a operação manual lenta ou inconsistente.",
    practicalUses: ["Monitoramento de preço e estoque", "Repricing com regras", "Alertas e histórico competitivo", "Comparação por canal"],
    metrics: ["Margem bruta", "Índice de preço", "Tempo gasto em repricing", "Conversão por faixa de preço"],
    attention: ["Automação deve respeitar margem mínima e política comercial", "Concorrência não deve ser o único sinal de preço", "Match incorreto de produto pode contaminar decisão e precisa ser auditado"],
    source: "https://prisync.com/ai-pricing-software/",
    sourceLabel: "Prisync — AI Pricing Software for Ecommerce",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "competera-ai-pricing",
    name: "AI Pricing Platform",
    company: "Competera",
    categorySlug: "precificacao",
    category: "Precificação",
    status: "Otimização de preço com IA contextual e human-in-the-loop",
    useCase: "Competera usa modelos de IA para recomendar preços a partir de múltiplos drivers de demanda, cenários e contexto competitivo, com suporte a otimização por produto, canal, categoria e loja.",
    bestFor: "Varejistas enterprise com muitos SKUs e necessidade de balancear receita, margem, elasticidade, posicionamento e consistência omnichannel.",
    practicalUses: ["Otimização baseada em elasticidade", "Simulação de cenários", "Precificação omnichannel", "Assistente de pricing com insights proativos"],
    metrics: ["Margem", "Receita incremental", "Elasticidade e precisão de forecast", "Tempo de repricing"],
    attention: ["A solução exige dados históricos e governança de preço", "Modelos devem operar com supervisão humana e regras estratégicas", "Resultado varia conforme categoria, qualidade dos dados e restrições comerciais"],
    source: "https://competera.ai/solutions/by-need/dynamic-pricing-optimization",
    sourceLabel: "Competera — AI-Driven Price Optimization",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "relex-forecasting-replenishment",
    name: "Forecasting & Replenishment",
    company: "RELEX Solutions",
    categorySlug: "logistica",
    category: "Logística e operação",
    status: "Previsão de demanda e reposição orientadas por IA",
    useCase: "RELEX conecta previsão de demanda e reposição automática para lojas, centros de distribuição e fornecedores, usando IA e machine learning para melhorar planejamento, disponibilidade e fluxo de estoque.",
    bestFor: "Varejo omnichannel, grocery e operações com rede de lojas ou CDs onde ruptura, excesso de estoque e previsão de demanda têm impacto financeiro relevante.",
    practicalUses: ["Forecast de demanda", "Reposição automática", "Planejamento de estoque", "Diagnóstico e exceções operacionais"],
    metrics: ["Acurácia do forecast", "Disponibilidade", "Ruptura", "Estoque e desperdício"],
    attention: ["Previsão precisa depende de histórico, promoções e dados externos bem tratados", "Resultados operacionais exigem integração com reposição e execução", "Modelos devem ser acompanhados por exceções e contexto comercial"],
    source: "https://www.relexsolutions.com/resources/ai-driven-retail-forecasting-and-replenishment/",
    sourceLabel: "RELEX — AI-driven retail forecasting and replenishment",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "google-analytics-ask-advisor",
    name: "Ask Advisor + Insights de IA",
    company: "Google Analytics",
    categorySlug: "analytics",
    category: "Analytics e BI",
    status: "Análise conversacional e insights gerados por IA",
    useCase: "O Google Analytics passou a combinar insights gerados por IA com o Ask Advisor, uma experiência conversacional baseada em Gemini para responder perguntas sobre a propriedade, gerar visualizações e apontar relatórios relevantes.",
    bestFor: "Times de e-commerce que já têm GA4 bem instrumentado e querem reduzir o tempo entre identificar uma mudança de performance e chegar a uma hipótese de investigação.",
    practicalUses: ["Resumir mudanças relevantes de performance", "Investigar compras, aquisição e comportamento em linguagem natural", "Explorar anomalias e sazonalidade", "Medir tráfego vindo de assistentes de IA"],
    metrics: ["Tempo para insight", "Cobertura e qualidade do tracking", "Receita por canal", "Conversões originadas por assistentes de IA"],
    attention: ["Ask Advisor está em beta", "A qualidade das respostas depende da qualidade da implementação do GA4", "Insights gerados não substituem validação de tracking, atribuição e contexto de negócio"],
    source: "https://support.google.com/analytics/answer/16675569?hl=pt-BR",
    sourceLabel: "Google Analytics Help — Ask Advisor (Beta)",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "semrush-ai-visibility",
    name: "AI Visibility Toolkit",
    company: "Semrush",
    categorySlug: "seo-geo",
    category: "Conteúdo, SEO e GEO",
    status: "Monitoramento de presença de marca em respostas de IA",
    useCase: "O AI Visibility Toolkit monitora menções, citações, percepção de marca, prompts e concorrentes em respostas de sistemas como ChatGPT, Gemini, Perplexity e experiências de IA do Google.",
    bestFor: "Marcas de e-commerce que querem medir presença em respostas generativas, descobrir lacunas de conteúdo e acompanhar se produtos e páginas estão sendo citados ou recomendados fora da busca tradicional.",
    practicalUses: ["Monitorar menções e citações em LLMs", "Comparar visibilidade com concorrentes", "Pesquisar prompts e temas", "Identificar problemas técnicos que podem bloquear crawlers de IA"],
    metrics: ["Menções em respostas de IA", "Páginas citadas", "Share of voice em prompts", "Tráfego e conversões de assistentes de IA"],
    attention: ["Métricas proprietárias da ferramenta não são equivalentes a ranking orgânico", "Visibilidade em IA deve ser analisada junto com tráfego e resultado de negócio", "Prompts e respostas podem variar por modelo, país, sessão e contexto"],
    source: "https://www.semrush.com/kb/1493-ai-visibility-toolkit",
    sourceLabel: "Semrush Knowledge Base — AI Visibility Toolkit",
    reviewedAt: "29/09/2026",
  },
  {
    slug: "meta-advantage-plus-creative",
    name: "Advantage+ Creative",
    company: "Meta",
    categorySlug: "ads",
    category: "Ads e aquisição",
    status: "Automação criativa e otimização de ativos com IA",
    useCase: "Advantage+ Creative aplica automações de criação e adaptação de anúncios, incluindo ajustes de formato, expansão de imagem com IA generativa e seleção automática de elementos para diferentes placements.",
    bestFor: "E-commerces que anunciam em Facebook e Instagram e precisam ampliar variações criativas e distribuição entre placements sem produzir manualmente cada adaptação.",
    practicalUses: ["Adaptação de criativos para placements", "Expansão generativa de imagem", "Seleção automatizada de música em formatos elegíveis", "Testes de variações criativas"],
    metrics: ["CPA", "ROAS", "CTR", "Conversão por placement e criativo"],
    attention: ["Automação criativa não substitui direção de marca", "Recursos podem variar por formato, mercado e conta", "É importante comparar desempenho incremental e revisar representações geradas antes de usar em escala"],
    source: "https://www.facebook.com/business/ads/facebook-instagram-reels-ads",
    sourceLabel: "Meta for Business — Reels Ads / Advantage+ Creative",
    reviewedAt: "29/09/2026",
  },
];

export const faqs = [
  {
    q: "Qual é a melhor IA para e-commerce em 2026?",
    a: "Não existe uma única ferramenta melhor para todas as operações. A escolha depende do gargalo: aquisição, atendimento, CRM, conteúdo, personalização, dados ou operação. O critério correto é impacto mensurável no negócio, compatibilidade com o stack e capacidade de governança.",
  },
  {
    q: "IA substitui a plataforma de e-commerce?",
    a: "Na maioria dos casos, não. A IA funciona como uma camada de inteligência sobre a plataforma, o catálogo, os dados e os canais de aquisição e relacionamento.",
  },
  {
    q: "O que é commerce agentivo?",
    a: "É um modelo em que agentes de IA participam diretamente da jornada de compra: entendem intenção, pesquisam, comparam, recomendam produtos e, em alguns fluxos, ajudam a concluir a transação.",
  },
  {
    q: "Como saber por onde começar?",
    a: "Comece pelo maior gargalo mensurável da operação. Atendimento alto, CAC crescente, baixa conversão, produção lenta de conteúdo e pouca retenção exigem ferramentas e integrações diferentes.",
  },
];

export const editorial = {
  updatedAt: "29/09/2026",
  publisher: "EyAgencia",
  methodology:
    "Selecionamos tecnologias com aplicação direta em e-commerce e priorizamos documentação oficial, disponibilidade verificável, clareza sobre limitações e potencial de impacto mensurável. Não usamos posição em listas pagas como critério editorial.",
};
